// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// -------------------- //
// scsi_host_async_read //
// -------------------- //

#define scsi_host_async_read_wrap_target 0
#define scsi_host_async_read_wrap 6
#define scsi_host_async_read_pio_version 0

static __pio_const uint16_t scsi_host_async_read_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x3009, //  2: wait   0 gpio, 9       side 1
    0x4009, //  3: in     pins, 9         side 0
    0x4067, //  4: in     null, 7         side 0
    0x2089, //  5: wait   1 gpio, 9       side 0
    0x1042, //  6: jmp    x--, 2          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program scsi_host_async_read_program = {
    .instructions = scsi_host_async_read_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = scsi_host_async_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config scsi_host_async_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_host_async_read_wrap_target, offset + scsi_host_async_read_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------------------------- //
// scsi_host_async_read_wide //
// ------------------------- //

#define scsi_host_async_read_wide_wrap_target 0
#define scsi_host_async_read_wide_wrap 6
#define scsi_host_async_read_wide_pio_version 0

static __pio_const uint16_t scsi_host_async_read_wide_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x3009, //  2: wait   0 gpio, 9       side 1
    0x4012, //  3: in     pins, 18        side 0
    0x406e, //  4: in     null, 14        side 0
    0x2089, //  5: wait   1 gpio, 9       side 0
    0x1042, //  6: jmp    x--, 2          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program scsi_host_async_read_wide_program = {
    .instructions = scsi_host_async_read_wide_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = scsi_host_async_read_wide_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config scsi_host_async_read_wide_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_host_async_read_wide_wrap_target, offset + scsi_host_async_read_wide_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// --------------------- //
// scsi_host_async_write //
// --------------------- //

#define scsi_host_async_write_wrap_target 0
#define scsi_host_async_write_wrap 17
#define scsi_host_async_write_pio_version 0

static __pio_const uint16_t scsi_host_async_write_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x90a0, //  2: pull   block           side 1
    0x3009, //  3: wait   0 gpio, 9       side 1
    0x7009, //  4: out    pins, 9         side 1
    0xb042, //  5: nop                    side 1
    0xb042, //  6: nop                    side 1
    0xb042, //  7: nop                    side 1
    0xb042, //  8: nop                    side 1
    0xb042, //  9: nop                    side 1
    0xb042, // 10: nop                    side 1
    0xb042, // 11: nop                    side 1
    0xb042, // 12: nop                    side 1
    0xa042, // 13: nop                    side 0
    0x2089, // 14: wait   1 gpio, 9       side 0
    0x1042, // 15: jmp    x--, 2          side 1
    0x5060, // 16: in     null, 32        side 1
    0x9020, // 17: push   block           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program scsi_host_async_write_program = {
    .instructions = scsi_host_async_write_program_instructions,
    .length = 18,
    .origin = -1,
    .pio_version = scsi_host_async_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config scsi_host_async_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_host_async_write_wrap_target, offset + scsi_host_async_write_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// -------------------------- //
// scsi_host_async_write_wide //
// -------------------------- //

#define scsi_host_async_write_wide_wrap_target 0
#define scsi_host_async_write_wide_wrap 17
#define scsi_host_async_write_wide_pio_version 0

static __pio_const uint16_t scsi_host_async_write_wide_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x90a0, //  2: pull   block           side 1
    0x3009, //  3: wait   0 gpio, 9       side 1
    0x7012, //  4: out    pins, 18        side 1
    0xb042, //  5: nop                    side 1
    0xb042, //  6: nop                    side 1
    0xb042, //  7: nop                    side 1
    0xb042, //  8: nop                    side 1
    0xb042, //  9: nop                    side 1
    0xb042, // 10: nop                    side 1
    0xb042, // 11: nop                    side 1
    0xb042, // 12: nop                    side 1
    0xa042, // 13: nop                    side 0
    0x2089, // 14: wait   1 gpio, 9       side 0
    0x1042, // 15: jmp    x--, 2          side 1
    0x5060, // 16: in     null, 32        side 1
    0x9020, // 17: push   block           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program scsi_host_async_write_wide_program = {
    .instructions = scsi_host_async_write_wide_program_instructions,
    .length = 18,
    .origin = -1,
    .pio_version = scsi_host_async_write_wide_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config scsi_host_async_write_wide_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_host_async_write_wide_wrap_target, offset + scsi_host_async_write_wide_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

